<?php
require_once './models/User.php';

$user = new User();
?>

<div class="tile is-parent">
    <div class="tile is-child box is-primary">
        <div class="card">
            <div class="card-content">

                <form action="/login.php" method="post" id="loginForm">
                    <div class="field">
                        <label class="label">Email</label>
                        <div class="control">
                            <input class="input" type="email" id="email" name="email" placeholder="Email" required="required">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Password</label>
                        <div class="control">
                            <input class="input" type="password" id="password" name="password" placeholder="Password" required="required">
                        </div>
                    </div>

                    <br/>

                    <div class="field">
                        <div class="control">
                            <button class="button is-danger is-fullwidth" id="loginButton">
                                Log In
                            </button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
