<div class="tile is-parent">
    <div class="tile is-child box has-background-light">
        <nav class="navbar" role="navigation" aria-label="Main Navigation">
            <div class="navbar-brand">
                <a class="navbar-item is-size-3 ml-4" href="#">
                    <strong class="has-text-black">Gaming Forum</strong>
                </a>
                <small class="navbar-item ml-3 has-text-danger-dark">Community for Players</small>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-success mr-6">
                            <span class="icon">
                                <i class="far fa-plus-square"></i>
                            </span>
                            <span>
                                <strong>New Post</strong>
                            </span>
                        </a>
                        <a class="button is-danger" href="../form.php?form=register">
                            <strong>Sign Up</strong>
                        </a>
                        <a class="button is-black" href="../form.php?form=login">
                            <strong>Log In</strong>
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</div>