<?php
require_once './models/Post.php';

$post = new Post();
?>

<div class="tile is-parent">
    <div class="tile is-child box is-primary">
        <table class="table is-fullwidth is-hoverable">
            <tr class="has-text-centered">
                <th>Title</th>
                <th>Author</th>
                <th>Time</th>
            </tr>

            <?php
            if (isset($_GET['topicId'])) {
                $topicId = htmlspecialchars($_GET['topicId']);
                $posts = $post->getAll($topicId);

                foreach ($posts as $post) {

                    echo '<tr class="has-text-centered">';
                    echo '<td>';

                    echo '<a href="post.php?topicId=' . $topicId . '&postId=' . $post->id . '">';

                    echo $post->title;

                    echo '</a>';

                    echo '</td>';

                    echo '<td>';

                    echo $post->firstName;?> <?php
                    echo $post->lastName;

                    echo '</td>';

                    echo '<td>';

                    $timestamp = strtotime($post->timestamp);
                    echo date( 'jS F Y',$timestamp);

                    echo '</td>';

                    echo '</tr>';
                }
            }
            ?>

        </table>
    </div>
</div>