<?php
require_once './models/User.php';

$user = new User();
?>

<div class="tile is-parent">
    <div class="tile is-child box is-primary">
        <div class="card">
            <div class="card-content">

                <form action="/register.php" method="post" id="registrationForm">
                    <div class="field">
                        <label class="label">First Name</label>
                        <div class="control">
                            <input class="input" type="text" id="firstName" name="firstName" placeholder="First Name" required="required">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Last Name</label>
                        <div class="control">
                            <input class="input" type="text" id="lastName" name="lastName" placeholder="Last Name" required="required">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Email</label>
                        <div class="control">
                            <input class="input" type="email" id="email" name="email" placeholder="Email" required="required">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Phone</label>
                            <div class="control">
                                <input class="input" type="tel" id="phone" name="phone" placeholder="Phone" required="required">
                            </div>
                    </div>

                    <div class="field">
                        <label class="label">Address</label>
                        <div class="control">
                            <input class="input" type="text" id="address" name="address" placeholder="Address">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Password</label>
                        <div class="control">
                            <input class="input" type="password" id="password" name="password" placeholder="Password" required="required">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Confirm Password</label>
                        <div class="control">
                            <input class="input" type="password" id="confPassword" name="confPassword" placeholder="Confrim Password" required="required">
                        </div>
                    </div>

                    <br/>

                    <div class="field">
                        <div class="control">
                            <button class="button is-danger is-fullwidth" id="registrationButton">
                                Sign Up
                            </button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
