<?php
    require_once './models/Topic.php';

    $topic = new Topic();
?>

<div class="tile is-3 is-vertical is-parent">
    <div class="tile is-child box">

        <table class="table is-fullwidth is-hoverable">
            <thead class="has-text-centered">
            <tr>
                <th class="is-info">Topic</th>
                <th class="is-info">Posts</th>
            </tr>
            </thead>

            <?php
            $topics = $topic->getAll();

            foreach ($topics as $topic) {
                echo '<tbody>';
                echo '<tr class="">';

                echo '<td>';

                echo '<a href="index.php?topicId=' . $topic->id . '">' . $topic->name . '</a>';

                echo '</td>';

                echo '<td class="has-text-centered">';

                echo $topic->postsCount;

                echo '</td>';

                echo '</tr>';
                echo '</tbody>';
            }
            ?>
        </table>
    </div>
</div>