<div class="tile is-3 is-vertical is-parent">
    <div class="tile is-child box">

        <table class="table is-fullwidth is-hoverable">
            <thead class="has-text-centered">
            <tr>
                <th class="is-info">Topic</th>
                <th class="is-info">Posts</th>
            </tr>
            </thead>

            <?php
            /** @noinspection PhpUndefinedVariableInspection */
            $topicArray = $db->getTopicTable();

            foreach ($topicArray as $topics) {
                echo '<tbody>';
                echo '<tr class="">';

                echo '<td>';

                echo '<a href="index.php?topicId=' . $topics->id . '">' . $topics->name . '</a>';

                echo '</td>';

                echo '<td class="has-text-centered">';

                echo $topics->postsCount;

                echo '</td>';

                echo '</tr>';
                echo '</tbody>';
            }
            ?>
        </table>
    </div>
</div>